### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by maitreyav**
Addresses #2

### CODE REVIEW

**Comment by TheAdnan** [comment]
Hey nice icon!
Could you edit the manifest.json and readme too, and I'll merge this PR?

**Comment by maitreyav** [comment]
@TheAdnan, Good to hear that. I have replaced the logo. Any other changes you'd recommend?

**Comment by maitreyav** [comment]
@TheAdnan, I'd like to know your thoughts.

**Comment by TheAdnan** [comment]
@maitreyav lovely, thanks

**Comment by maitreyav** [comment]
Welcome! I'd love to contribute more for this. 😄  Is it on Chrome yet?

**Comment by TheAdnan** [comment]
It's not, not yet. @adnanrahic is currently assigned to this issue, but you can make a PR and I'll review your commits and merge both.

**Comment by maitreyav** [comment]
@TheAdnan, Sure. I'll see what I can do. 👍

**Pull request merged**
